### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ucsky** [Image-Science-Lab-cmu/Precise-Forecasting-of-Sky-Images-Using-Spatial-Warping#1]
Hi,
I try to run `train.py` but I got the following error:
```
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    inputs = Variable(data[0]).to(device) # The input data
  File "train.py", line 94, in run_train
    G_output = model(x)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/skynet_Unet_model.py", line 93, in forward
    x1 = self.inc(x)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/skynet_Unet_model.py", line 28, in forward
    x = self.conv(x)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/skynet_Unet_model.py", line 19, in forward
    x=self.conv(x)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/worker/.miniconda3/envs/SkyNet/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
Do you known how to fix this?

**Comment by leronjulian** [comment]
Hi, can you let me know a few things:

1. Your version of PyTorch
2. Your version of CUDA
3. What model GPU are you training on

**Comment by ucsky** [comment]
Hi, Thanks for the help, yes sure:
1. The version of PyTorch is 1.3.1:
```
(SkyNet) worker@2901af2c40ee:~$ python
Python 2.7.17 |Anaconda, Inc.| (default, Oct 21 2019, 19:04:46) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.3.1'
```
2.  The version of cuda is 12
```
(SkyNet) worker@2901af2c40ee:~$ nvidia-smi 
Wed Oct 25 16:03:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  On   | 00000000:17:00.0 Off |                    0 |
| N/A   42C    P0    42W / 250W |      4MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
3. The GPU is a NVIDIA A100-PCIE-40GB

I run it using docker with image `pytorch/pytorch:1.3-cuda10.1-cudnn7-devel`

**Comment by leronjulian** [comment]
I think you should try to remove and reinstall the packages based on your specific CUDA versions on your computer. Packages such torch, cupy, etc. should all be downloaded based on your CUDA version. You have CUDA version 12 but it looks like the Pytorch-CUDA version in the requirements.txt file is PyTorch-CUDA 10.1


Also update to a newer version of Python ~3.11. Can help solve those issues. I will update the README soon
